[package]
name = "dynrs"
version = "0.1.0"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
phf = { version = "0.10.0", features = ["macros"] }
ureq = "2.2.0"
