[package]
name = "dynrs"
version = "0.1.1"
authors = ["koopa1338 <sinner1991@gmail.com>"]
edition = "2021"

[dependencies]
dotenv = "0.15"
dotenv_codegen = "0.15"
phf = { version = "0.11", features = ["macros"] }
ureq = "2.6"
